//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtomatikController.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        public int ıd { get; set; }
        public int KisilerId { get; set; }
        public string Adres1 { get; set; }
        public string Sehir { get; set; }
    }
}
