//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtomatikController.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kisiler
    {
        public int ıd { get; set; }
        public string İsim { get; set; }
        public string Soyisim { get; set; }
        public Nullable<int> Adres { get; set; }
    }
}
